### ISSUE TITLE
AtomSpace benchmark throws RuntimeException

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1289]
Running this command:

`opencog/benchmark/atomspace_bm -A`

results in:

```
Benchmarking AtomSpace's addLink method 100000 times ....terminate called after throwing an instance of 'opencog::RuntimeException'
  what():  AtomTable - Atom in outgoing set isn't known! (/home/opencog/src/opencog/opencog/atomspace/AtomTable.cc:569)

Program received signal SIGABRT, Aborted.
0x00007ffff5e43cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5e43cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff5e470d8 in __GI_abort () at abort.c:89
#2  0x00007ffff696d6b5 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff696b836 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff696b863 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff696baa2 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff74eacbb in opencog::AtomTable::add (this=this@entry=0x6693f0, 
    atom=..., async=async@entry=false)
    at /home/opencog/src/opencog/opencog/atomspace/AtomTable.cc:570
#7  0x00007ffff74dd1f7 in opencog::AtomSpaceImpl::addLink (this=0x6693f0, 
    t=30, outgoing=..., tvn=..., async=async@entry=false)
    at /home/opencog/src/opencog/opencog/atomspace/AtomSpaceImpl.cc:220
#8  0x0000000000410a3d in addLink (
    tvn=<error reading variable: access outside bounds of object referenced via synthetic pointer>, outgoing=..., t=<optimized out>, this=<optimized out>)
    at /home/opencog/src/opencog/opencog/atomspace/AtomSpace.h:159
#9  opencog::AtomSpaceBenchmark::makeRandomLink (this=0x7fffffffea30)
---Type <return> to continue, or q <return> to quit---
    at /home/opencog/src/opencog/opencog/benchmark/AtomSpaceBenchmark.cc:578
#10 0x0000000000410c69 in opencog::AtomSpaceBenchmark::bm_addLink (
    this=<optimized out>)
    at /home/opencog/src/opencog/opencog/benchmark/AtomSpaceBenchmark.cc:653
#11 0x0000000000411c6f in opencog::AtomSpaceBenchmark::doBenchmark (
    this=this@entry=0x7fffffffea30, methodName=..., 
    methodToCall=<optimized out>)
    at /home/opencog/src/opencog/opencog/benchmark/AtomSpaceBenchmark.cc:269
#12 0x00000000004122b8 in opencog::AtomSpaceBenchmark::startBenchmark (
    this=this@entry=0x7fffffffea30, numThreads=numThreads@entry=1)
    at /home/opencog/src/opencog/opencog/benchmark/AtomSpaceBenchmark.cc:354
#13 0x000000000040c31e in main (argc=2, argv=0x7fffffffec28)
    at /home/opencog/src/opencog/opencog/benchmark/atomspace_bm.cc:169
```

**Comment by linas** [comment]
OK, I can reproduce this ... I think I almost see where the bug is too.   Very odd ...

**Comment by inflector** [comment]
fix verified
