### ISSUE TITLE
5 tests failed

### ISSUE THREAD

**Issue by aurelien-rainone** [opencog/opencog#1456]
i want to inform you that i have been running the tests on the most recent codebase as the time of writing, BUT with the small modification I proposed in this pull request : https://github.com/opencog/opencog/pull/1455 as without it, I couldn't compile UseCountUTest, that is now pasing

So these tests failed : 
77:TemporalUTest
78:TemporalMapUTest
92:AllPythonModuleTests
108:interpreterUTest
131:dynFeatSelUTest

here the detailed build/tests/Testing/Temporary/LastTest.log ouptput for these failed tests : 

**TemporalUTest**
77/158 Testing: TemporalUTest
77/158 Test: TemporalUTest
Command: "/home/panty/Documents/dev/opencog/src/build/tests/spatial/TemporalUTest"
Directory: /home/panty/Documents/dev/opencog/src/build/tests/spatial
"TemporalUTest" start time: Mar 25 15:33 CET
Output:
----------------------------------------------------------
Running cxxtest tests (5 tests)
In TemporalUTest::testConstructor:
/home/panty/Documents/dev/opencog/src/tests/spatial/TemporalUTest.cxxtest:51: Error: Test failed: Temporal - Upper bound reached when creating a Temporal (normal-distribution): 0. (/home/panty/Documents/dev/opencog/src/opencog/spacetime/Temporal.cc:69)
In TemporalUTest::testGettersAndPrinters:
/home/panty/Documents/dev/opencog/src/tests/spatial/TemporalUTest.cxxtest:109: Error: Test failed: Temporal - Upper bound reached when creating a Temporal (normal-distribution): 10. (/home/panty/Documents/dev/opencog/src/opencog/spacetime/Temporal.cc:69)
In TemporalUTest::testCompareToAndComparisonOperators:
/home/panty/Documents/dev/opencog/src/tests/spatial/TemporalUTest.cxxtest:155: Error: Test failed: Temporal - Upper bound reached when creating a Temporal (normal-distribution): 0. (/home/panty/Documents/dev/opencog/src/opencog/spacetime/Temporal.cc:69)
In TemporalUTest::testClone:
/home/panty/Documents/dev/opencog/src/tests/spatial/TemporalUTest.cxxtest:342: Error: Test failed: Temporal - Upper bound reached when creating a Temporal (normal-distribution): 1. (/home/panty/Documents/dev/opencog/src/opencog/spacetime/Temporal.cc:69)
In TemporalUTest::testTimeNodeNameConversionMethods:
/home/panty/Documents/dev/opencog/src/tests/spatial/TemporalUTest.cxxtest:359: Error: Test failed: Temporal - Upper bound reached when creating a Temporal (normal-distribution): 1. (/home/panty/Documents/dev/opencog/src/opencog/spacetime/Temporal.cc:69)
Failed 5 and Skipped 0 of 5 tests 
Success rate: 0%
<end of output>
Test time =   0.06 sec
----------------------------------------------------------
Test Failed.
"TemporalUTest" end time: Mar 25 15:33 CET
"TemporalUTest" time elapsed: 00:00:00
----------------------------------------------------------

**TemporalTableUTest**
78/158 Testing: TemporalMapUTest
78/158 Test: TemporalMapUTest
Command: "/home/panty/Documents/dev/opencog/src/build/tests/spatial/TemporalMapUTest"
Directory: /home/panty/Documents/dev/opencog/src/build/tests/spatial
"TemporalMapUTest" start time: Mar 25 15:33 CET
Output:
----------------------------------------------------------
terminate called after throwing an instance of 'opencog::InvalidParamException'
  what():  Temporal - Upper bound reached when creating a Temporal (normal-distribution): 0. (/home/panty/Documents/dev/opencog/src/opencog/spacetime/Temporal.cc:69)
<end of output>
Test time =   1.16 sec
----------------------------------------------------------
Test Failed.
"TemporalMapUTest" end time: Mar 25 15:33 CET
"TemporalMapUTest" time elapsed: 00:00:01
----------------------------------------------------------

79/158 Testing: TemporalTableUTest
79/158 Test: TemporalTableUTest
Command: "/home/panty/Documents/dev/opencog/src/build/tests/spatial/TemporalTableUTest"
Directory: /home/panty/Documents/dev/opencog/src/build/tests/spatial
"TemporalTableUTest" start time: Mar 25 15:33 CET
Output:
----------------------------------------------------------
Running cxxtest tests (22 tests)......................OK!
<end of output>
Test time =   0.09 sec
----------------------------------------------------------
Test Passed.
"TemporalTableUTest" end time: Mar 25 15:33 CET
"TemporalTableUTest" time elapsed: 00:00:00
----------------------------------------------------------

**AllPythonModuleTests**
92/158 Testing: AllPythonModuleTests
92/158 Test: AllPythonModuleTests
Command: "/usr/bin/nosetests" "-vs" "--with-doctest" "/home/panty/Documents/dev/opencog/src/tests/python/"
Directory: /home/panty/Documents/dev/opencog/src/build/tests/python
"AllPythonModuleTests" start time: Mar 25 15:34 CET
Output:
----------------------------------------------------------
Testing the bfs function ... SKIP: Unit test disabled, see: https://github.com/opencog/opencog/issues/1280
test_conjunctions (test_anaphora.AnaphoraUnitTester) ... ok
Testing the getWords function ... ok
test_pleonastic_if (test_anaphora.AnaphoraUnitTester) ... ok
Testing the propose function ... SKIP: Unit test disabled, see: https://github.com/opencog/opencog/issues/1280
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
Failure: SkipTest (Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442) ... SKIP: Unit test temporarily disabled - see: https://github.com/opencog/opencog/issues/442
test_all (test_rules_new.PLNUnitTester) ... FAIL
Failure: SkipTest (ImportError exception: make sure the required dependencies are installed.) ... SKIP: ImportError exception: make sure the required dependencies are installed.

======================================================================
FAIL: test_all (test_rules_new.PLNUnitTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/panty/Documents/dev/opencog/src/tests/python/test_pln/test_rules_new.py", line 96, in test_all
    self.run_file(testFile)
  File "/home/panty/Documents/dev/opencog/src/tests/python/test_pln/test_rules_new.py", line 268, in run_file
    self.verify_result()
  File "/home/panty/Documents/dev/opencog/src/tests/python/test_pln/test_rules_new.py", line 247, in verify_result
    self.assertTrue(allPredictedItemsExist and allItemsWerePredicted)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 10 tests in 3.568s

FAILED (SKIP=6, failures=1)
Testing file: /home/panty/Documents/dev/opencog/src/tests/python/test_pln/new_scm_tests/AndRule_new.scm
Checking if all predicted items were created:
  Yes, all predicted items exist
Checking if all created items were predicted:
  Yes, all created items were predicted
Testing file: /home/panty/Documents/dev/opencog/src/tests/python/test_pln/new_scm_tests/BooleanTransformationRule_new.scm
Checking if all predicted items were created:
  Yes, all predicted items exist
Checking if all created items were predicted:
  Yes, all created items were predicted
Testing file: /home/panty/Documents/dev/opencog/src/tests/python/test_pln/new_scm_tests/DeductionRule_InheritanceLink.scm
Checking if all predicted items were created:
  Yes, all predicted items exist
Checking if all created items were predicted:
  Yes, all created items were predicted
Testing file: /home/panty/Documents/dev/opencog/src/tests/python/test_pln/new_scm_tests/InheritanceRule.scm
Checking if all predicted items were created:
  Yes, all predicted items exist
Checking if all created items were predicted:
  Yes, all created items were predicted
Testing file: /home/panty/Documents/dev/opencog/src/tests/python/test_pln/new_scm_tests/AbductionRule_InheritanceLink.scm
Checking if all predicted items were created:
Unable to find
(InheritanceLink (av 0 0 0) (stv 0.252525 1.000000)
  (ConceptNode "Socrates" (av 0 0 0) (stv 0.010000 1.000000)) ;
  (ConceptNode "Human" (av 0 0 0) (stv 0.010000 1.000000)) ;
) ;

  No, not all predicted items were created (see above for details)
Checking if all created items were predicted:
Unable to find
(InheritanceLink (av 0 0 0) (stv 0.252525 1.000000)
  (ConceptNode "Human" (av 0 0 0) (stv 0.010000 1.000000)) ;
  (ConceptNode "Socrates" (av 0 0 0) (stv 0.010000 1.000000)) ;
) ;
  No, some created items were not predicted (see above for details)
<end of output>
Test time =   3.84 sec
----------------------------------------------------------
Test Failed.
"AllPythonModuleTests" end time: Mar 25 15:34 CET
"AllPythonModuleTests" time elapsed: 00:00:03
----------------------------------------------------------

**interpreterUTest**
108/158 Testing: interpreterUTest
108/158 Test: interpreterUTest
Command: "/home/panty/Documents/dev/opencog/src/build/tests/comboreduct/combo/interpreterUTest"
Directory: /home/panty/Documents/dev/opencog/src/build/tests/comboreduct/combo
"interpreterUTest" start time: Mar 25 15:34 CET
Output:
----------------------------------------------------------
Running cxxtest tests (3 tests)inputs = 2 2 2, expected output = false, returned output = false
inputs = 2 1 1, expected output = false, returned output = false
inputs = 2 1 2, expected output = true, returned output = true
inputs = 1 2 2, expected output = true, returned output = true
.inputs = 1 2 0 0 1 0 0, expected output = 13, returned output = 13
inputs = 0 0 3 4 1 0 0, expected output = 11.75, returned output = 11.75

In interpreterUTest::test_contin_interpreter:
/home/panty/Documents/dev/opencog/src/tests/comboreduct/combo/interpreterUTest.cxxtest:76: Error: Expected (res == ir.second), found (12.6094 != 12.6094)
inputs = 0 0 0 0 5 0 0, expected output = 12.6094, returned output = 12.6094
inputs = 0 0 0 0 1 6 0, expected output = 413.429, returned output = 413.429
/home/panty/Documents/dev/opencog/src/tests/comboreduct/combo/interpreterUTest.cxxtest:76: Error: Expected (res == ir.second), found (11.6569 != 11.6569)
inputs = 0 0 0 0 1 0 7, expected output = 11.657, returned output = 11.657
inputs = 1 2 3 4 5 6 7, expected output = 418.445, returned output = 418.445
inputs = 1 2 true, expected output = 0.841471, returned output = 0.841471
inputs = 1 -2 true, expected output = 0, returned output = 0
inputs = 1 2 false, expected output = 0, returned output = 0
.
Failed 1 and Skipped 0 of 3 tests
Success rate: 66%
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"interpreterUTest" end time: Mar 25 15:34 CET
"interpreterUTest" time elapsed: 00:00:00
----------------------------------------------------------

**dynFeatSelUTest**

131/158 Testing: dynFeatSelUTest
131/158 Test: dynFeatSelUTest
Command: "/home/panty/Documents/dev/opencog/src/build/tests/learning/moses/dynFeatSelUTest"
Directory: /home/panty/Documents/dev/opencog/src/build/tests/learning/moses
"dynFeatSelUTest" start time: Mar 25 15:50 CET
Output:
----------------------------------------------------------
Running cxxtest tests (4 tests)tempfile /tmp/mosesUTestpkJdIM
-20 or(and(or(and($16 $84) and(!$30 !$89 !$167 !$290)) or($16 !$84 $134) !$31 !$130 !$218 !$251 !$275) and($16 $71 !$200) $27 $39 $272)

In dynamicFeatsUTest::test_dyn_feat_score:
/home/panty/Documents/dev/opencog/src/tests/learning/moses/moses-framework.h:216: Error: Assertion failed: f_it != expected_tr_strs.end()
Wallclock time: 00:00:28.034341
tempfile /tmp/mosesUTest6DPC1o
-20 or(and(or(and($16 $84) and(!$30 !$89 !$167 !$290)) or($16 !$84 $134) !$31 !$130 !$218 !$251 !$275) and($16 $71 !$200) $27 $39 $272)
In dynamicFeatsUTest::test_dyn_feat_score_threaded:
/home/panty/Documents/dev/opencog/src/tests/learning/moses/moses-framework.h:216: Error: Assertion failed: f_it != expected_tr_strs.end()
Wallclock time: 00:00:24.022391
tempfile /tmp/mosesUTesta8bpam
Wallclock time: 00:00:12.413422
.tempfile /tmp/mosesUTestNfPR6Z
Wallclock time: 00:00:01.821816
.
Failed 2 and Skipped 0 of 4 tests
Success rate: 50%
<end of output>
Test time =  66.44 sec
----------------------------------------------------------
Test Failed.
"dynFeatSelUTest" end time: Mar 25 15:51 CET
"dynFeatSelUTest" time elapsed: 00:01:06
----------------------------------------------------------

**Comment by linas** [comment]
You mention in #1455 that you are on a 32-bit machine. I am guessing that the remaining test fails are for similar/the same reasons: incompatibilities with int vs long int

**Comment by aurelien-rainone** [comment]
most probably, yes
i can further investigate and submit a pull request

2015-03-25 18:05 GMT+01:00 Linas Vepštas <notifications@github.com>:

**Comment by aurelien-rainone** [comment]
**dynFeatSelUTest** is now the only that fails, the other were indeed due to 32bits/64bits timestamp inconsistencies, that should be fixed now with #1466

I'll have a look at **dynFeatSelUTest** tomorrow

**Comment by aurelien-rainone** [comment]
That does the trick, it removes the warnings on both 32 and 64 bits machines.

Though i was trying to avoid the use architecture-dependent integer types, thinking that one day opencog can run on a 128bits architecture!
Or to not rely on types at all, with the use of std::ostringstream or boost::format for example.
Now i don't want to nitpick :smile:  and there are also possible performances considerations about the use of these 2 methods

**Comment by linas** [comment]
On Fri, Mar 27, 2015 at 9:19 AM, Aurelien Rainone <notifications@github.com>
wrote:

> one day opencog can run on a 128bits architecture!
>
Are you saying you want to port opencog to an IBM AS/400 ?

**Comment by aurelien-rainone** [comment]
not necessarily... ;-)

2015-03-27 19:01 GMT+01:00 Linas Vepštas <notifications@github.com>:

**Comment by aurelien-rainone** [comment]
Closing the issue, 4/5 test pass now, the remaining being **AllPythonModuleTests** that has its own issue : #1162 (that is closed but should be reopened i think)
(http://158.132.58.86:8010/builders/opencog_master_trusty/builds/406/steps/test/logs/stdio)

**Comment by inflector** [comment]
Aurelien, I'd create a new issue for it. The cause of the failure at that
time was different than the one we are seeing now. If you reopen the test,
then people looking at it will think the old bug reappeared. This is a new
bug so it should get a new issue so it can be assigned to the right person.


On Sun, Mar 29, 2015 at 10:56 AM, Aurelien Rainone <notifications@github.com

**Comment by aurelien-rainone** [comment]
Curtis, you are right, i was not aware of the fact that the cause of the failure were different.
So i'm creating a new issue
