### ISSUE TITLE
RestApiTest fail

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2141]
this is on a current ubuntu 14.04 system.

log output:

````
31/39 Test: RestApiTest
Command: "/usr/local/bin/nosetests" "-vs" "--with-doctest" "/home/biocog/opencog/tests/python/restapi"
Directory: /home/biocog/opencog/build/tests/python
"RestApiTest" start time: May 04 14:24 EDT
Output:
----------------------------------------------------------
test_restapi.TestRESTApi.test_delete_link ... ERROR
test_restapi.TestRESTApi.test_delete_node ... ERROR
test_restapi.TestRESTApi.test_dot_export ... ERROR
test_restapi.TestRESTApi.test_get_atoms_by_av ... ERROR
test_restapi.TestRESTApi.test_get_types ... ERROR
test_restapi.TestRESTApi.test_include_incoming_outgoing ... ERROR
test_restapi.TestRESTApi.test_post_and_get_link ... ERROR
test_restapi.TestRESTApi.test_post_and_get_node ... ERROR
test_restapi.TestRESTApi.test_post_revise_existing_link ... ERROR
test_restapi.TestRESTApi.test_post_revise_existing_node ... ERROR
test_restapi.TestRESTApi.test_put_and_get_tv_av_link ... ERROR
test_restapi.TestRESTApi.test_put_and_get_tv_av_node ... ERROR
test_restapi.TestRESTApi.test_scheme_command ... ERROR
test_restapi.TestRESTApi.test_tv_filter ... ERROR

======================================================================
ERROR: test_restapi.TestRESTApi.test_delete_link
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/biocog/opencog/tests/python/restapi/test_restapi.py", line 43, in setUp
    self.bird.av = {'sti': 9}
  File "opencog/atom.pyx", line 89, in opencog.atomspace.Atom.av.__set__ (/home/biocog/hansonrobotics/opencog/atomspace/build/opencog/cython/opencog/atomspace.cpp:9708)
UnboundLocalError: local variable 'lti' referenced before assignment
````
the traceback with the "UnboundLocalError" is identical for all 14 sub-tests.

**Comment by mjsduncan** [comment]
working through the python shell as described in the [wiki](http://wiki.opencog.org/w/REST_APIl) seems to work as described with no errors...

**Comment by linas** [comment]
is this still an issue?

**Comment by AmeBel** [comment]
Closing fixed by https://github.com/opencog/opencog/pull/2200
