### ISSUE TITLE
Cogserver crashes when exiting a guile shell

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2564]
To reproduce it, start the cogserver:
```scm
scheme@(guile-user)> (use-modules (opencog) (opencog cogserver))
scheme@(guile-user)> (start-cogserver "path/to/the/default/opencog.conf")
Listening on port 17001
$1 = "Started CogServer"
```

Then telnet to it, start and exit guile:
```bash
$ rlwrap telnet localhost 17001
opencog> scm
guile> .
opencog> Connection closed by foreign host.
```

It crashes:
```
Core was generated by `guile'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f865f6f5cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  0x00007f865f6f5cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f865f6f90d8 in __GI_abort () at abort.c:89
#2  0x00007f865b55a535 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f865b5586d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f865b558703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f8652b2448a in ~thread (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/thread:143
#6  opencog::GenericShell::~GenericShell (this=0x7f863c000c10, __in_chrg=<optimized out>)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/shell/GenericShell.cc:82
#7  0x00007f8652b25b29 in opencog::SchemeShell::~SchemeShell (this=0x7f863c000c10, 
    __in_chrg=<optimized out>)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/shell/SchemeShell.cc:59
#8  0x00007f8652b23a20 in opencog::GenericShell::eval (this=0x7f863c000c10, expr=...)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/shell/GenericShell.cc:268
#9  0x00007f8655972fe9 in opencog::ConsoleSocket::OnLine (this=0x7f86480009d0, line=...)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/ConsoleSocket.cc:163
#10 0x00007f8655970fee in opencog::ServerSocket::handle_connection (this=0x7f86480009d0)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/ServerSocket.cc:163
#11 0x00007f865b5aba40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f865fa8c182 in start_thread (arg=0x7f8651907700) at pthread_create.c:312
#13 0x00007f865f7b947d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

Tested with:
cogutils `commit faf6b395a0b3dc76876119627fbdfb8c78cf61f7`
atomspace `commit d7549e7c136a3882c874e1c58a69ad9f93fb5a88` 
opencog `commit 706bf0c020ea78c19dcdddc4863d0c7f01a799be`

**Comment by linas** [comment]
Oops. Fixed in #2565 and tested in #2566  closing, I think its fixed.

**Comment by leungmanhin** [comment]
thanks!

**Comment by linas** [comment]
I also fixed a crash when you control-C in the telnet terminal.

cntrol-C should now work, to stop scheme/phython processes. It won't stop C++ though.

**Comment by leungmanhin** [comment]
Yeah that's nice, ctrl-c is working too, thanks a lot

**Comment by leungmanhin** [comment]
Oh wait... it crashes when exiting the python shell:
```
GenericShell.cc:165: virtual void opencog::GenericShell::eval(const string&): Assertion `not self_destruct' failed.
```

**Comment by linas** [comment]
temp work around is to comment out the assert that make it crash. I will look and fix tomorrow.

**Comment by linas** [comment]
I think this is fixed. Let me know if not.

**Comment by linas** [comment]
closing
