### ISSUE TITLE
Segfault when loading the ECAN module

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2570]
In the opencog shell, when I do:
```
loadmodule path/to/opencog/build/opencog/attention/libattention.so
```

It crashes:
```
Core was generated by `guile -l btree-psi.scm'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f76344ab36e in setAttentionalFocusBoundary (this=0x0, s=150)
    at /usr/local/include/opencog/attentionbank/AttentionBank.h:231
231	        _attentionalFocusBoundary = s;
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
(gdb) bt
#0  0x00007f76344ab36e in setAttentionalFocusBoundary (this=0x0, s=150)
    at /usr/local/include/opencog/attentionbank/AttentionBank.h:231
#1  opencog::FocusBoundaryUpdatingAgent::FocusBoundaryUpdatingAgent (this=0x7f76900045d0, cs=...)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/attention/FocusBoundaryUpdatingAgent.cc:57
#2  0x00007f763449e421 in opencog::Factory<opencog::FocusBoundaryUpdatingAgent, opencog::Agent>::create
    (this=<optimized out>, cs=...)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/Factory.h:71
#3  0x00007f7724168a06 in opencog::Registry<opencog::Agent>::create (this=this@entry=0x43ee928, cs=..., 
    id=...) at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/Registry.h:103
#4  0x00007f7724165f7e in opencog::CogServer::createAgent (this=0x43ee920, id=..., 
    start=start@entry=false)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/CogServer.cc:298
#5  0x00007f763449d455 in opencog::AttentionModule::AttentionModule (this=0x7f76900019d0, cs=...)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/attention/AttentionModule.cc:59
#6  0x00007f763449da21 in opencog_module_load (cogserver=...)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/attention/AttentionModule.cc:35
#7  0x00007f77241678fa in opencog::CogServer::loadModule (this=0x43ee920, filename=...)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/CogServer.cc:470
#8  0x00007f76e4175f8f in opencog::LoadModuleRequest::execute (this=0x7f7664008e90)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/LoadModuleRequest.cc:55
#9  0x00007f7724165904 in opencog::CogServer::processRequests (this=this@entry=0x43ee920)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/CogServer.cc:264
#10 0x00007f7724165c62 in opencog::CogServer::runLoopStep (this=0x43ee920)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/CogServer.cc:227
#11 0x00007f7724165b5d in opencog::CogServer::serverLoop (this=0x43ee920)
    at /home/hr/hansonrobotics/opencog/opencog/opencog/cogserver/server/CogServer.cc:201
#12 0x00007f774fe26a40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007f7753a61182 in start_thread (arg=0x7f76a77fe700) at pthread_create.c:312
#14 0x00007f775378e47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by linas** [comment]
I just pushed changeset d9ec3a02a67e5dc375b2d617221b9573183a8d64  which should fix this.  It is possible that some of the other agents are missing this line of code.

**Comment by leungmanhin** [comment]
Just checked the other agents as well, they look good to me, thanks!
