### ISSUE TITLE
mst-parse-text Seg Faults processing 6,000 sentences

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#2785]
While running a new perl script, `mst-one.pl` analogous to `submit-one.pl` in `/nlp/learn/run`, I am getting consistent segmentation faults, albeit in non-deterministic locations. The script `mst-one.pl` just calls `netcat` once for each line in a file calling a function which, in turn, calls `mst-parse-text` and writes four values per line to a csv file (see code for `mst-write` below).

This script does a heavy test of the asynchronous use of guile and the atomspace since it creates many separate threads each handling a separate call to `mst-parse-text` for individual sentences using the threading mechanism provided by ConsoleSocket in the CogServer when calling scheme functions via netcat. There are no AtomSpace writes since `mst-parse-text` is just reading atoms to get mutual information for word pairs, in this case using the `clique-pair-api`. 

NOTE: I had to manually change mst-parse-text to use this api for my purposes by adjusting mi-source at the top of mst-parse-text:
```
(define-public (mst-parse-text plain-text)

	; the source of where we will get MI from
	; (define mi-source (add-pair-freq-api (make-any-link-api)))
	(define mi-source (add-pair-freq-api (make-clique-pair-api)))
```

I generally can't get my script to process more than about 1,000 to 2,000 sentences before getting a segfault, unless I run with gdb attached to the guile process, then it completes, albeit at a much slower rate of processing. The only time I have had the full 5933 sentences process successfully, is when gdb was running and attached to guile.

That the segfaults don't appear when running in gdb indicates that the problem is likely some sort of race condition or other multi-threading issue that is sensitive to timing.

Much of the time there is no backtrace dumped but there is one in the logfile:
```

[2017-06-19 05:23:21:570] [ERROR] Caught signal 11 (Segmentation fault) on thread 140069100820224
	Stack Trace:
	2: basic_string.h:539	~basic_string()
	3: CogServerMain.cc:81	_Z7sighandi()
	4: ??:0	killpg()
	5: pairs.h:159	scm_is_pair()
	6: vm-engine.c:787	vm_regular_engine()
	7: vm.c:1258	scm_call_n()
	8: eval.c:502	scm_call_3()
	9: vm-engine.c:787	vm_regular_engine()
	10: vm.c:1258	scm_call_n()
	11: throw.c:139	catch()
	12: SchemeEval.cc:573	  opencog::SchemeEval::do_eval(std::string const&)
	13: SchemeEval.cc:503	  opencog::SchemeEval::c_wrap_eval(void*)
	14: continuations.c:422	c_body()
	15: vm-engine.c:787	vm_regular_engine()
	16: vm.c:1258	scm_call_n()
	17: throw.c:139	catch()
	18: continuations.c:367	scm_i_with_continuation_barrier()
	19: continuations.c:461	scm_c_with_continuation_barrier()
	20: pthread_support.c:1341	GC_call_with_gc_active()
	21: threads.c:689	with_guile()
	22: misc.c:1938	GC_call_with_stack_base()
	23: threads.c:710	scm_with_guile()
	24: SchemeEval.cc:474	  opencog::SchemeEval::eval_expr(std::string const&)
	25: GenericShell.cc:500	  opencog::GenericShell::eval_loop()
	26: ??:0	  std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)
	27: pthread_create.c:312	start_thread()
	28: clone.S:113	clone()

```
and here is another one, this one from a backtrace generated by looking at the coredump
```

(gdb) bt
#0  scm_is_pair (x=0x0) at ../libguile/pairs.h:159
#1  scm_iprlist (hdr=hdr@entry=0x7f850285dc52 "(", exp=exp@entry=0x171cfea0, 
    tlr=tlr@entry=41, port=port@entry=0x1eb1140, pstate=pstate@entry=0x1d90160)
    at print.c:973
#2  0x00007f8502802660 in iprin1 (exp=0x171cfea0, port=0x1eb1140, 
    pstate=0x1d90160) at print.c:636
#3  0x00007f8502801ae9 in scm_prin1 (exp=exp@entry=0x171cfea0, 
    port=port@entry=0x1eb1140, writingp=writingp@entry=1) at print.c:817
#4  0x00007f85028029c1 in scm_write (obj=obj@entry=0x171cfea0, 
    port=port@entry=0x1eb1140) at print.c:1076
#5  0x00007f8502827c79 in scm_object_to_string (obj=0x171cfea0, printer=0x904)
    at strports.c:232
#6  0x00007f8502833908 in vm_debug_engine (thread=0x1f42540, vp=0x171676c0, 
    registers=0x0, resume=2) at vm-engine.c:784
#7  0x00007f850283e076 in scm_call_n (proc=0x10359e0, 
    argv=argv@entry=0x7f82d27f30e0, nargs=nargs@entry=4) at vm.c:1257
#8  0x00007f85027c07b4 in scm_call_4 (proc=<optimized out>, 
    arg1=arg1@entry=0x1c31760, arg2=arg2@entry=0x4, arg3=arg3@entry=0xfab6e0, 
    arg4=arg4@entry=0x1490e30) at eval.c:508
#9  0x00007f85027b2233 in scm_print_exception (port=port@entry=0x1c31760, 
    frame=frame@entry=0x4, key=key@entry=0xfab6e0, args=args@entry=0x1490e30)
    at backtrace.c:113
#10 0x00007f85027b22cf in error_during_backtrace (data=0x1c31760, 
    tag=0xfab6e0, throw_args=0x1490e30) at backtrace.c:257
#11 0x00007f8502833908 in vm_debug_engine (thread=0x1f42540, vp=0x171676c0, 
    registers=0x0, resume=2) at vm-engine.c:784
#12 0x00007f850283e076 in scm_call_n (proc=proc@entry=0x1c31720, 
    argv=0x7f82d27f3320, nargs=5) at vm.c:1257
#13 0x00007f85027c0acb in scm_apply_0 (proc=proc@entry=0x1c31720, args=0x304)
    at eval.c:594
#14 0x00007f850282cacd in catch (tag=tag@entry=0x404, thunk=0x1c31740, 
    handler=0x1c31720, pre_unwind_handler=0x4) at throw.c:134
#15 0x00007f850282ce05 in scm_catch_with_pre_unwind_handler (
    key=key@entry=0x404, thunk=<optimized out>, handler=<optimized out>, 
    pre_unwind_handler=<optimized out>) at throw.c:254
#16 0x00007f850282cfbf in scm_c_catch (tag=tag@entry=0x404, 
    body=body@entry=0x7f85027b1ea0 <display_backtrace_body>, 
    body_data=body_data@entry=0x7f82d27f34f0, 
    handler=handler@entry=0x7f85027b22a0 <error_during_backtrace>, 
    handler_data=<optimized out>, 
    pre_unwind_handler=pre_unwind_handler@entry=0x0, 
    pre_unwind_handler_data=pre_unwind_handler_data@entry=0x0) at throw.c:377
#17 0x00007f850282cfd4 in scm_internal_catch (tag=tag@entry=0x404, 
    body=body@entry=0x7f85027b1ea0 <display_backtrace_body>, 
    body_data=body_data@entry=0x7f82d27f34f0, 
    handler=handler@entry=0x7f85027b22a0 <error_during_backtrace>, 
    handler_data=<optimized out>) at throw.c:386
#18 0x00007f85027b1e94 in scm_display_backtrace_with_highlights (
    stack=<optimized out>, port=<optimized out>, first=<optimized out>, 
    depth=<optimized out>, highlights=<optimized out>) at backtrace.c:282
#19 0x00007f84f95410be in opencog::SchemeEval::catch_handler (
    this=0x7f8344000990, tag=0x100c140, throw_args=<optimized out>)
    at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:420
#20 0x00007f8502833908 in vm_debug_engine (thread=0x1f42540, vp=0x171676c0, 
    registers=0x0, resume=2) at vm-engine.c:784
#21 0x00007f850283e076 in scm_call_n (proc=proc@entry=0x16eb42e0, 
    argv=0x7f82d27f3780, nargs=5) at vm.c:1257
#22 0x00007f85027c0acb in scm_apply_0 (proc=proc@entry=0x16eb42e0, args=0x304)
    at eval.c:594
#23 0x00007f850282cacd in catch (tag=<optimized out>, thunk=0x16eb4300, 
    handler=0x16eb42e0, pre_unwind_handler=0x16eb42c0) at throw.c:134
#24 0x00007f84f953e858 in opencog::SchemeEval::do_eval (this=0x7f8344000990, 
    expr=...) at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:572
#25 0x00007f84f953e973 in opencog::SchemeEval::c_wrap_eval (p=0x7f8344000990)
    at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:501
#26 0x00007f85027ba73a in c_body (d=0x7f82d27f3d30) at continuations.c:422
#27 0x00007f8502833908 in vm_debug_engine (thread=0x1f42540, vp=0x171676c0, 
    registers=0x0, resume=2) at vm-engine.c:784
#28 0x00007f850283e076 in scm_call_n (proc=proc@entry=0x16eb4720, 
    argv=argv@entry=0x0, nargs=nargs@entry=0) at vm.c:1257
#29 0x00007f85027c0719 in scm_call_0 (proc=proc@entry=0x16eb4720) at eval.c:481
#30 0x00007f850282caea in catch (tag=tag@entry=0x404, thunk=0x16eb4720, 
    handler=0x16eb4700, pre_unwind_handler=0x16eb46e0) at throw.c:137
#31 0x00007f850282ce05 in scm_catch_with_pre_unwind_handler (
    key=key@entry=0x404, thunk=<optimized out>, handler=<optimized out>, 
    pre_unwind_handler=<optimized out>) at throw.c:254
#32 0x00007f850282cfbf in scm_c_catch (tag=tag@entry=0x404, 
    body=body@entry=0x7f85027ba730 <c_body>, 
    body_data=body_data@entry=0x7f82d27f3d30, 
    handler=handler@entry=0x7f85027ba9d0 <c_handler>, 
    handler_data=handler_data@entry=0x7f82d27f3d30, 
    pre_unwind_handler=pre_unwind_handler@entry=0x7f85027ba830 <pre_unwind_handler>, pre_unwind_handler_data=pre_unwind_handler_data@entry=0x1002020)
    at throw.c:377
#33 0x00007f85027bad2f in scm_i_with_continuation_barrier (
    body=body@entry=0x7f85027ba730 <c_body>, 
    body_data=body_data@entry=0x7f82d27f3d30, 
    handler=handler@entry=0x7f85027ba9d0 <c_handler>, 
    handler_data=handler_data@entry=0x7f82d27f3d30, 
    pre_unwind_handler=pre_unwind_handler@entry=0x7f85027ba830 <pre_unwind_handler>, pre_unwind_handler_data=0x1002020) at continuations.c:360
#34 0x00007f85027badc5 in scm_c_with_continuation_barrier (
    func=<optimized out>, data=<optimized out>) at continuations.c:456
#35 0x00007f8501f3e705 in GC_call_with_gc_active (
    fn=fn@entry=0x7f850282ad00 <with_guile_trampoline>, 
    client_data=client_data@entry=0x7f82d27f3e00) at pthread_support.c:1339
#36 0x00007f850282b6f1 in with_guile (base=base@entry=0x7f82d27f3dd0, 
    data=data@entry=0x7f82d27f3e00) at threads.c:688
#37 0x00007f8501f38632 in GC_call_with_stack_base (
    fn=fn@entry=0x7f850282b660 <with_guile>, arg=arg@entry=0x7f82d27f3e00)
    at misc.c:1935
#38 0x00007f850282ba48 in scm_i_with_guile (dynamic_state=<optimized out>, 
    data=<optimized out>, func=<optimized out>) at threads.c:703
#39 scm_with_guile (func=<optimized out>, data=<optimized out>)
    at threads.c:709
#40 0x00007f84f953e91e in opencog::SchemeEval::eval_expr (this=0x7f8344000990, 
    expr=...) at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:473
#41 0x00007f84e79c6f86 in opencog::GenericShell::eval_loop (
    this=0x7f83e0012560)
    at /home/inflector/oc/opencog/opencog/cogserver/shell/GenericShell.cc:453
#42 0x00007f84f8152a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#43 0x00007f850255f184 in start_thread (arg=0x7f82d27f4700)
    at pthread_create.c:312
#44 0x00007f850228cbed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
and the second time I got a good coredump, I looked at the command being passed to eval_expr to see if the sentence gave any clue as to the problem. It did, I think.

```
#36 0x00007f8a7303b91e in opencog::SchemeEval::eval_expr (this=0x7f8980000990, 
    expr=...) at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:473
473		scm_with_guile(c_wrap_eval, this);
(gdb) list
468		}
469	
470		_pexpr = &expr;
471		_in_shell = true;
472		_in_eval = true;
473		scm_with_guile(c_wrap_eval, this);
474		_in_eval = false;
475		_in_shell = false;
476	}
477	
(gdb) print *(char**) _pexpr
$2 = 0x7f897400f398 "(mst-write \"“My dear Miss Elizabeth, I have the highest opinion in the world in your excellent judgement in all matters within the scope of your understanding; but permit me to say, that there must "...
```
The scheme function mst-write is defined here:

```
(define (first-index line) (caar (cadr line)))
(define (second-index line) (caadr (cadr line)))
(define (first-name line) (cog-name (cadar (cadr line))))
(define (second-name line) (cog-name (cadadr (cadr line))))

(define (write-parse-lines parse-lines out_port)
	(for-each
		(lambda (line)
			(write (first-index line) out_port)
			(display ", " out_port)
			(write (first-name line) out_port)
			(display ", " out_port)
			(write (second-index line) out_port)
			(display ", " out_port)
			(write  (second-name line) out_port)
			(newline out_port)
		)
		parse-lines
	)
)

(define (mst-write sentence out_file)
	(write-parse-lines (mst-parse-text sentence) out_file)
)
```

All `mst-write` does is extract out pieces of the mst parse and write them to the port defined by the out_file binding.

**NOTE: Further testing shows sentence length is not directly related to the crash. See follow-on messages below.**

I searched for this text in the input file to check the number of words in the sentence and found:

> “My dear Miss Elizabeth, I have the highest opinion in the world in your excellent judgement in all matters within the scope of your understanding; but permit me to say, that there must be a wide difference between the established forms of ceremony amongst the laity, and those which regulate the clergy; for, give me leave to observe that I consider the clerical office as equal in point of dignity with the highest rank in the kingdom--provided that a proper humility of behaviour is at the same time maintained.

This sentence has 89 words. The average number of words per sentence in this test is 25. And 89 words is a long sentence for a recursive sentence parsing algorithm. The other time I looked at the sentence and noted that it too was long, though I didn't check the specific sentence, since this was just the first occurrence in a test that includes many long sentences. So it wasn't until the second occurrence that I noted the actual sentence.

A working hypothesis is that long sentences make it more likely that the race condition / problem will occur.

It also appears from the backtraces that the segfault comes from a corruption that causes an exception to be thrown or that results from an exception being thrown since it appears to be attempting to print a backtrace when the segfault occurs because of internal corruption of one of the SCM pairs. All the crashes end up in a call to scm_is_pair() so far.

Another clue may come from the printout for the parsing which has odd return characters interspersed (returned by the mst-parse-text?) with an occasional #f. Here is the output for the crash above:
```

Processed sentence -   100 - 0 seconds, average 0.0096



#f
Processed sentence -   200 - 4 seconds, average 0.0245








Processed sentence -   300 - 18 seconds, average 0.0620




Processed sentence -   400 - 43 seconds, average 0.1086









Processed sentence -   500 - 70 seconds, average 0.1411






Processed sentence -   600 - 105 seconds, average 0.1752




Processed sentence -   700 - 131 seconds, average 0.1882


Processed sentence -   800 - 161 seconds, average 0.2024




Processed sentence -   900 - 219 seconds, average 0.2439












Processed sentence -  1000 - 267 seconds, average 0.2674







Processed sentence -  1100 - 338 seconds, average 0.3080








Processed sentence -  1200 - 486 seconds, average 0.4055



Processed sentence -  1300 - 590 seconds, average 0.4544




Processed sentence -  1400 - 741 seconds, average 0.5299










Processed sentence -  1500 - 856 seconds, average 0.5711









Processed sentence -  1600 - 1014 seconds, average 0.6343









Processed sentence -  1700 - 1117 seconds, average 0.6574







Processed sentence -  1800 - 1329 seconds, average 0.7384


Processed sentence -  1900 - 1446 seconds, average 0.7612
Processed sentence -  2000 - 1446 seconds, average 0.7232
Processed sentence -  2100 - 1446 seconds, average 0.6888
Processed sentence -  2200 - 1446 seconds, average 0.6576

```
Here is a more recent coredump and another sentence:
```

(gdb) bt
#0  0x00007fd52cefa418 in scm_is_pair (x=<optimized out>)
    at ../libguile/pairs.h:159
#1  vm_debug_engine (thread=0x7fd52d1641e0 <atomics_lock>, vp=0x21dff30, 
    registers=0x4, resume=4) at vm-engine.c:2353
#2  0x00007fd52cf05076 in scm_call_n (proc=0x7fd523be34a8, 
    argv=argv@entry=0x7fd4d5f9e5d0, nargs=nargs@entry=3) at vm.c:1257
#3  0x00007fd52ce8777f in scm_call_3 (proc=<optimized out>, 
    arg1=<optimized out>, arg2=<optimized out>, arg3=<optimized out>)
    at eval.c:501
#4  0x00007fd52cefa908 in vm_debug_engine (
    thread=0x7fd52d1641e0 <atomics_lock>, vp=0x21dff30, registers=0x4, 
    resume=4) at vm-engine.c:784
#5  0x00007fd52cf05076 in scm_call_n (proc=proc@entry=0x205f660, 
    argv=argv@entry=0x0, nargs=nargs@entry=0) at vm.c:1257
#6  0x00007fd52ce87719 in scm_call_0 (proc=proc@entry=0x205f660) at eval.c:481
#7  0x00007fd52cef3aea in catch (tag=<optimized out>, thunk=0x205f660, 
    handler=0x205f640, pre_unwind_handler=0x205f620) at throw.c:137
#8  0x00007fd523c05858 in opencog::SchemeEval::do_eval (this=0x7fd434000990, 
    expr=...) at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:572
#9  0x00007fd523c05973 in opencog::SchemeEval::c_wrap_eval (p=0x7fd434000990)
    at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:501
#10 0x00007fd52ce8173a in c_body (d=0x7fd4d5f9ed30) at continuations.c:422
#11 0x00007fd52cefa908 in vm_debug_engine (
    thread=0x7fd52d1641e0 <atomics_lock>, vp=0x21dff30, registers=0x4, 
    resume=4) at vm-engine.c:784
#12 0x00007fd52cf05076 in scm_call_n (proc=proc@entry=0x205fc60, 
    argv=argv@entry=0x0, nargs=nargs@entry=0) at vm.c:1257
#13 0x00007fd52ce87719 in scm_call_0 (proc=proc@entry=0x205fc60) at eval.c:481
#14 0x00007fd52cef3aea in catch (tag=tag@entry=0x404, thunk=0x205fc60, 
    handler=0x205fc40, pre_unwind_handler=0x205fc00) at throw.c:137
#15 0x00007fd52cef3e05 in scm_catch_with_pre_unwind_handler (
    key=key@entry=0x404, thunk=<optimized out>, handler=<optimized out>, 
    pre_unwind_handler=<optimized out>) at throw.c:254
#16 0x00007fd52cef3fbf in scm_c_catch (tag=tag@entry=0x404, 
    body=body@entry=0x7fd52ce81730 <c_body>, 
    body_data=body_data@entry=0x7fd4d5f9ed30, 
    handler=handler@entry=0x7fd52ce819d0 <c_handler>, 
    handler_data=handler_data@entry=0x7fd4d5f9ed30, 
    pre_unwind_handler=pre_unwind_handler@entry=0x7fd52ce81830 <pre_unwind_handler>, pre_unwind_handler_data=pre_unwind_handler_data@entry=0x1864020)
    at throw.c:377
#17 0x00007fd52ce81d2f in scm_i_with_continuation_barrier (
    body=body@entry=0x7fd52ce81730 <c_body>, 
    body_data=body_data@entry=0x7fd4d5f9ed30, 
    handler=handler@entry=0x7fd52ce819d0 <c_handler>, 
    handler_data=handler_data@entry=0x7fd4d5f9ed30, 
    pre_unwind_handler=pre_unwind_handler@entry=0x7fd52ce81830 <pre_unwind_handler>, pre_unwind_handler_data=0x1864020) at continuations.c:360
#18 0x00007fd52ce81dc5 in scm_c_with_continuation_barrier (
    func=<optimized out>, data=<optimized out>) at continuations.c:456
#19 0x00007fd52c605705 in GC_call_with_gc_active (
    fn=fn@entry=0x7fd52cef1d00 <with_guile_trampoline>, 
    client_data=client_data@entry=0x7fd4d5f9ee00) at pthread_support.c:1339
#20 0x00007fd52cef26f1 in with_guile (base=base@entry=0x7fd4d5f9edd0, 
    data=data@entry=0x7fd4d5f9ee00) at threads.c:688
#21 0x00007fd52c5ff632 in GC_call_with_stack_base (
    fn=fn@entry=0x7fd52cef2660 <with_guile>, arg=arg@entry=0x7fd4d5f9ee00)
    at misc.c:1935
#22 0x00007fd52cef2a48 in scm_i_with_guile (dynamic_state=<optimized out>, 
    data=<optimized out>, func=<optimized out>) at threads.c:703
#23 scm_with_guile (func=<optimized out>, data=<optimized out>)
    at threads.c:709
#24 0x00007fd523c0591e in opencog::SchemeEval::eval_expr (this=0x7fd434000990, 
    expr=...) at /home/inflector/oc/atomspace/opencog/guile/SchemeEval.cc:473
#25 0x00007fd51608ef86 in opencog::GenericShell::eval_loop (
    this=0x7fd430000c80)
    at /home/inflector/oc/opencog/opencog/cogserver/shell/GenericShell.cc:453
#26 0x00007fd522819a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#27 0x00007fd52cc26184 in start_thread (arg=0x7fd4d5f9f700)
    at pthread_create.c:312
#28 0x00007fd52c953bed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```

The last crash is interesting and provides another clue. It crashed much earlier in the process, on the fifth sentence processed in the test file:

> However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.

Here are the first few sentences:

> 
> PRIDE AND PREJUDICE
> <P>
> By Jane Austen
> <P>
> Chapter 1
> <P>
> It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.
> <P>
> However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered the rightful property of some one or other of their daughters.

The output shows that more than 600 sentences were processed (note: whitespace lines, about 20 or so, have been removed from the below):
```
Processed sentence -   100 - 1 seconds, average 0.0101
Processed sentence -   200 - 4 seconds, average 0.0244
Processed sentence -   300 - 18 seconds, average 0.0619
Processed sentence -   400 - 43 seconds, average 0.1098
Processed sentence -   500 - 69 seconds, average 0.1399
Processed sentence -   600 - 103 seconds, average 0.1726
```
Since there are 60 threads created in ConsoleSocket.cc:
`unsigned int ConsoleSocket::_max_open_sockets = 60;`

and each socket creates it's own thread which takes commands from the netcat input from the perl script feeding it sentences; so because of the likely O(n^2) parsing algorithm, it appears that the 550 or more shorter sentences are finished parsing before the fifth sentence is done parsing, since the fifth sentence is the first large sentence in the test file and will take much longer than any of the mostly shorter sentences.

So I suspect that short sentences all finish until we reach a point where there are only long sentences being parsed and at this point, with 60 long sentences being processed simultaneously, a crash is likely.

**Comment by inflector** [comment]
Okay, so I ran a few more tests and eliminated some possibilities. 

First, the size of the sentence may be stressing the system in some way, but a test of all large sentences (at or near the average of 56 words per sentence) did not crash in 3000 seconds. So this is not just a resource problem caused by the size of the sentences.

Second, as the test runs, the threads back up with large sentences. The smaller sentences are processed orders of magnitude more quickly so time is dominated by large sentences, so their presence in the crashes may simply be due to their taking all the time so the probability of any random segfault happening in a large sentence is much higher for that reason. Times for parses of four or five word sentences are in the low millisecond range while parsing for 60+ word sentences are in the 5 to 10 second range on a 6-core cpu.

**Comment by inflector** [comment]
Last segfault with a much shorter, 27-word, sentence:

> He had rather hoped that his wife’s views on the stranger would be disappointed; but he soon found out that he had a different story to hear.

Supporting the idea that the segfault is NOT directly caused by longer sentences, though there might be some interaction with total guile SCM objects created which will be more with greater recursion.

**Comment by inflector** [comment]
I eliminated the file writes and implemented a similar set of functions that just count the lines in the parses instead of writing them.
```

(define line_count 0)
(define (increment_line_count count) (set! line_count (+ line_count count)) #f)
(define parse_count 0)
(define (increment_parse_count) (set! parse_count (+ parse_count 1)) #f)

(define (count-parse-lines parse-lines)
    (define parse_line_count 0)
    (define (count_one_line) (set! parse_line_count (+ parse_line_count 1)) #f)
    (for-each
        (lambda (line)
            (count_one_line)
        )
        parse-lines
    )
    (increment_line_count parse_line_count)
)

(define (mst-count sentence)
    (count-parse-lines (mst-parse-text sentence))
    (increment_parse_count)
)
```

This still segfaults, though this particular test lasted much longer than other previous tests, except the gdb watched tests. It segfaulted procesing sentence 1547 while the highest line processed was more than 4000. So it was still processing the (poorly-split) 92-word sentence:

> If you should have no objection to receive me into your house, I propose myself the satisfaction of waiting on you and your family, Monday, November 18th, by four o’clock, and shall probably trespass on your hospitality till the Saturday se’ennight following, which I can do without any inconvenience, as Lady Catherine is far from objecting to my occasional absence on a Sunday, provided that some other clergyman is engaged to do the duty of the day.--I remain, dear sir, with respectful compliments to your lady and daughters, your well-wisher and friend,

while some of the threads were processing 2500 lines later.

The segfault backtrace was in the same location as one of the above.

**Comment by inflector** [comment]
Did some profiling and tracing on mst-parse-text and found it had a time profile of:

time = (words-in-sentence)^4.85

when curve fitting the following sample times:

```
# Words     Time(s)
-------     -------
49              2.0s
92             29.0s
140           219.0s
184           819.0s

```
Guile profiling of the 22-word sentence, "The gentlemen pronounced him to be a fine figure of a man, the ladies declared he was much handsomer than Mr. Bingley", shows:
```
scheme@(guile-user)> ,profile (mst-parse-text "The gentlemen pronounced him to be a fine figure of a man, the ladies declared he was much handsomer than Mr. Bingley") #:count-calls? #t
%     cumulative   self             
time   seconds    seconds   calls   procedure
 30.77      0.13      0.13   29808  procedure?
 26.92      0.11      0.11   28953  equal?
 15.38      0.32      0.06   28855  opencog/nlp/learn/mst-parser.scm:277:24
 11.54      0.05      0.05    4511  cog-link
  7.69      0.03      0.03    1981  cog-value
  3.85      0.02      0.02    1981  opencog/nlp/learn/batch-word-pair.scm:217:16:get-pair
  3.85      0.02      0.02   29510  srfi/srfi-1.scm:835:0:any1
  0.00      0.67      0.00     321  srfi/srfi-1.scm:590:5:map1
  0.00      0.41      0.00       1  opencog/nlp/learn/mst-parser.scm:164:0:mst-parse-text
  0.00      0.32      0.00     361  filter
  0.00      0.13      0.00   29510  srfi/srfi-1.scm:823:0:any
  0.00      0.10      0.00      23  opencog/nlp/learn/mst-parser.scm:250:8:pick-best-cost-pair
  0.00      0.08      0.00    2254  opencog/nlp/learn/mst-parser.scm:326:24
  0.00      0.08      0.00    1981  opencog/analysis/object-api.scm:512:16:get-pair-fmi
  0.00      0.08      0.00     252  srfi/srfi-1.scm:687:0:filter-map
  0.00      0.08      0.00      21  srfi/srfi-1.scm:678:0:append-map
  0.00      0.02      0.00      23  srfi/srfi-1.scm:458:2:fold
  0.00      0.02      0.00    2530  opencog/nlp/learn/mst-parser.scm:96:0:safe-pair-mi
  0.00      0.02      0.00     276  opencog/nlp/learn/mst-parser.scm:200:24
  0.00      0.00      0.00       1  set-vm-trace-level!
  0.00      0.00      0.00     252  opencog/nlp/learn/mst-parser.scm:359:24
  0.00      0.00      0.00    1981  cog-value-ref
  0.00      0.00      0.00       1  <current input>:18:9
  0.00      0.00      0.00    4013  anon #x7fbe9e7b7070
  0.00      0.00      0.00       1  anon #x7fbe9e7b7010
  0.00      0.00      0.00     895  opencog/nlp/learn/mst-parser.scm:72:8:strip-sufli
  0.00      0.00      0.00     895  opencog/nlp/learn/mst-parser.scm:385:21
  0.00      0.00      0.00      23  length
  0.00      0.00      0.00      24  opencog/nlp/learn/mst-parser.scm:277:24
  0.00      0.00      0.00       1  ice-9/eval.scm:590:16
  0.00      0.00      0.00      22  opencog/nlp/learn/mst-parser.scm:87:8:strip-affix
  0.00      0.00      0.00       2  ice-9/eval.scm:282:4
  0.00      0.00      0.00    1606  opencog/nlp/learn/mst-parser.scm:53:8:strip-prefli
  0.00      0.00      0.00       2  substring
  0.00      0.00      0.00       1  ice-9/eval.scm:191:12
  0.00      0.00      0.00    1981  opencog/analysis/object-api.scm:603:16
  0.00      0.00      0.00      46  list?
  0.00      0.00      0.00    1981  opencog/nlp/learn/batch-word-pair.scm:265:16
  0.00      0.00      0.00       1  anon #x7fbe9e7b7078
  0.00      0.00      0.00      29  cog-new-node
  0.00      0.00      0.00     250  opencog/nlp/learn/mst-parser.scm:278:42
  0.00      0.00      0.00       1  vm-trace-level
  0.00      0.00      0.00      24  nlp/types/nlp_types.scm:9:0:WordNode
  0.00      0.00      0.00     252  reverse!
  0.00      0.00      0.00       3  opencog/atoms/base/core_types.scm:427:0:PredicateNode
  0.00      0.00      0.00       1  opencog/analysis/object-api.scm:369:0:add-pair-freq-api
  0.00      0.00      0.00     174  opencog/nlp/learn/mst-parser.scm:406:25
  0.00      0.00      0.00      47  opencog/nlp/learn/mst-parser.scm:278:42
  0.00      0.00      0.00      22  concatenate
  0.00      0.00      0.00       1  ice-9/eval.scm:330:13
  0.00      0.00      0.00      23  srfi/srfi-1.scm:586:2:map
  0.00      0.00      0.00       2  nlp/types/nlp_types.scm:14:0:AnyNode
  0.00      0.00      0.00     250  opencog/nlp/learn/mst-parser.scm:277:24
  0.00      0.00      0.00       1  anon #x7fbe9e7b706c
  0.00      0.00      0.00       2  string->list
  0.00      0.00      0.00       1  statprof.scm:263:4:profile-signal-handler
  0.00      0.00      0.00       1  opencog/nlp/learn/batch-word-pair.scm:195:0:make-clique-pair-api
  0.00      0.00      0.00       1  statprof.scm:219:0:existing-profiler-state
  0.00      0.00      0.00       1  statprof.scm:333:0:statprof-stop
  0.00      0.00      0.00   28855  opencog/nlp/learn/mst-parser.scm:278:42
  0.00      0.00      0.00       1  string-split
  0.00      0.00      0.00      24  opencog/nlp/learn/mst-parser.scm:180:24
  0.00      0.00      0.00       2  string
  0.00      0.00      0.00       1  statprof.scm:863:0:call-thunk
  0.00      0.00      0.00       1  opencog/nlp/learn/mst-parser.scm:42:0:tokenize-text
  0.00      0.00      0.00      71  append
---
Sample count: 26
Total time: 0.4120575 seconds (0.0 seconds in GC)
```

**Comment by inflector** [comment]
Thr asynchronous processing using perl script text input via netcat masks the very long times of some of the parses due to an algorithm / implementation that is of O(n^4.85) because the sentences appear to be processing at a higher rate because some of the threads are being processed faster and returning to the script so that progress is reported based on asynchronous completion rates in the aggregate.

A side-effect that may be relevant is that garbage collection is happening several times per parse in larger sentences.

**Comment by linas** [comment]
Can you please verify these results?  I did an extensive set of measurements, and was only able to witness O(n^3) behavior, and never O(n^4.85).  Even so, I made a change to limit link lengths, which, for me, brought the speed down to O(n^2.3) for sentences longer than 16 words.   This change was done in commit 73ef7388bc3a61657492cdf8aec57d0a38db41c  on approx Aug 10th.

**Comment by linas** [comment]
Closing, there have been redesigns which alleviate the problems, I believe.  The guile crash has been reported  in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27234  

In order for the guile people to fix the bug, we need a simple test case to trigger it. That report explains how to write such a test case, but someone has to actually do it.
