### ISSUE TITLE
AnaphoraTest fail on clean ubuntu 16.04

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2793]
for atomspace commit 1b9a0c5 and opencog commit e1c3697

ImportError (/home/mjsd/oc/opencog/build/opencog/cython/opencog/cogserver_type_constructors.so: undefined symbol: embodiment_types_init)
````
ERROR: Failure: ImportError (/home/mjsd/oc/opencog/build/opencog/cython/opencog/cogserver_type_constructors.so: undefined symbol: embodiment_types_init)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/mjsd/oc/opencog/tests/nlp/anaphora/test_anaphora.py", line 8, in <module>
    from opencog.cogserver_type_constructors import types
ImportError: /home/mjsd/oc/opencog/build/opencog/cython/opencog/cogserver_type_constructors.so: undefined symbol: embodiment_types_init
````

**Comment by linas** [comment]
Try doing a git pull, and rebuilding.  The missing file, `embodiment_types_init` was recently removed.
