### ISSUE TITLE
RestApiTest fails on ubuntu 16.04

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2989]
1 test out of 7 fails: `FAIL: test_restapi.TestRESTApi.test_g_delete_node`
```
21/27 Test: RestApiTest
Command: "/usr/bin/nosetests" "-vs" "--with-doctest" "/home/mjsd/oc/opencog/tests/python/restapi"
Directory: /home/mjsd/oc/opencog/build/tests/python
"RestApiTest" start time: Jan 24 11:39 EST
Output:
----------------------------------------------------------
/home/mjsd/oc/opencog/opencog/python/web/api/apiatomcollection.py:4: ExtDeprecationWarning: Importing flask.ext.restful is deprecated, use flask_restful instead.
  from flask.ext.restful import Resource, reqparse, marshal
/home/mjsd/oc/opencog/opencog/python/web/api/apiatomcollection.py:4: ExtDeprecationWarning: Importing flask.ext.restful.reqparse is deprecated, use flask_restful.reqparse instead.
  from flask.ext.restful import Resource, reqparse, marshal
/home/mjsd/oc/opencog/opencog/python/web/api/mappers.py:12: ExtDeprecationWarning: Importing flask.ext.restful.fields is deprecated, use flask_restful.fields instead.
  from flask.ext.restful import fields, marshal
/home/mjsd/oc/opencog/opencog/python/web/api/apiatomcollection.py:8: ExtDeprecationWarning: Importing flask.ext.restful.utils is deprecated, use flask_restful.utils instead.
  from flask.ext.restful.utils import cors
/home/mjsd/oc/opencog/opencog/python/web/api/apiatomcollection.py:8: ExtDeprecationWarning: Importing flask.ext.restful.utils.cors is deprecated, use flask_restful.utils.cors instead.
  from flask.ext.restful.utils import cors
test_restapi.TestRESTApi.test_a_post_and_get_node ... ok
test_restapi.TestRESTApi.test_b_post_and_get_link ... ok
test_restapi.TestRESTApi.test_c_put_and_get_tv_av_node ... ok
test_restapi.TestRESTApi.test_d_put_and_get_tv_av_link ... ok
test_restapi.TestRESTApi.test_e_post_revise_existing_node ... ok
test_restapi.TestRESTApi.test_f_post_revise_existing_link ... ok
test_restapi.TestRESTApi.test_g_delete_node ... FAIL
test_restapi.TestRESTApi.test_h_delete_link ... ok
test_restapi.TestRESTApi.test_j_get_types ... ok
test_restapi.TestRESTApi.test_k_tv_filter ... ok
test_restapi.TestRESTApi.test_l_include_incoming_outgoing ... ok
test_restapi.TestRESTApi.test_m_scheme_command ... ok
test_restapi.TestRESTApi.test_n_dot_export ... ok

======================================================================
FAIL: test_restapi.TestRESTApi.test_g_delete_node
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mjsd/oc/opencog/tests/python/restapi/test_restapi.py", line 368, in test_g_delete_node
    assert delete_result['success']
AssertionError

----------------------------------------------------------------------
Ran 13 tests in 0.188s

FAILED (failures=1)
{u'truthvalue': {u'type': u'simple', u'details': {u'count': 0.4, u'strength': 0.5}}, u'outgoing': [2, 4], u'type': u'InheritanceLink'}
{u'truthvalue': {u'type': u'simple', u'details': {u'count': 0.9, u'strength': 1.0}}, u'outgoing': [9, 12], u'type': u'InheritanceLink'}
{u'truthvalue': {u'type': u'simple', u'details': {u'count': 0.9, u'strength': 1.0}}, u'outgoing': [16, 19], u'type': u'InheritanceLink'}
{u'truthvalue': {u'type': u'simple', u'details': {u'count': 0.95, u'strength': 0.1}}, u'outgoing': [16, 19], u'type': u'InheritanceLink'}
{u'truthvalue': {u'type': u'simple', u'details': {u'count': 0.9, u'strength': 1.0}}, u'outgoing': [22, 25], u'type': u'InheritanceLink'}
<end of output>
Test time =   0.36 sec
----------------------------------------------------------
Test Failed.
"RestApiTest" end time: Jan 24 11:39 EST
"RestApiTest" time elapsed: 00:00:00
----------------------------------------------------------
```

**Comment by linas** [comment]
closing, this is a stale bug report
