### ISSUE TITLE
Python -- cogserver crashes

### ISSUE THREAD

**Issue by linas** [opencog/opencog#3226]
After a clean rebuild and reinstall, coserver will not run; it crashes because python is not found or not installed or something.
```                                     
ImportError: No module named atomspace
Segmentation fault
```

Under GDB:
```
(gdb) bt
#0  0x00007fffe828af2c in PyDict_SetItem ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#1  0x00007fffe828b074 in PyDict_SetItemString ()
   from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#2  0x00007fffe86bf2cd in opencog::PythonEval::initialize_python_objects_and_im$orts (this=this@entry=0x13e5960)
    at /home/ubuntu/src/atomspace/opencog/cython/PythonEval.cc:519
#3  0x00007fffe86c10f0 in opencog::PythonEval::PythonEval (this=0x13e5960, 
    atomspace=0xe22bd0)
    at /home/ubuntu/src/atomspace/opencog/cython/PythonEval.cc:401
#4  0x00007fffe86c11db in opencog::PythonEval::create_singleton_instance (
    atomspace=0xe22bd0)
    at /home/ubuntu/src/atomspace/opencog/cython/PythonEval.cc:434
#5  0x00007fffe7aee762 in opencog::CogServer::CogServer (this=0x13a7ef0, 
    as=<optimized out>)
    at /home/ubuntu/src/opencog/opencog/cogserver/server/CogServer.cc:144
#6  0x00007fffe7aee971 in opencog::CogServer::createInstance (as=0xe22bd0, 
    as@entry=<error reading variable: value has been optimized out>)
    at /home/ubuntu/src/opencog/opencog/cogserver/server/CogServer.cc:77
#7  0x00007fffe7ae940c in opencog::server (factoryFunction=<optimized out>, 
    as=as@entry=0xe22bd0)
```

**Comment by linas** [comment]
When I fix the null-pointer deref, I get:
```
[2018-06-26 20:13:33:067] [INFO] [global_python_initialize] Start
[2018-06-26 20:13:33:079] [INFO] [global_python_initialize] Adding OpenCog sys.p
ath directories
[2018-06-26 20:13:33:080] [WARN] PythonEval::try_to_load_modules Failed to load 
the opencog.atomspace module
[2018-06-26 20:13:33:080] [INFO] [global_python_initialize] Finish
[2018-06-26 20:13:33:080] [INFO] [global_python_initialize] Start
[2018-06-26 20:13:33:080] [WARN] PythonEval::atomspace_py_object Failed to load theopencog.atomspace module
```
and then it hangs

**Comment by linas** [comment]
Closing .. Pull req opencog/atomspace#1781 fixes this .. remaining python issues in a different bug report.
