### ISSUE TITLE
PLN backward chaining triggers segmentation fault in Atom::getTruthValue for atom handle that was already removed

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#522]
***Steps to reproduce:***
Clone this repo: **https://github.com/cosmoharrigan/opencog/tree/pln-bc**
Rebuild opencog
and then run these commands:
```
cd ~/opencog/opencog/python/pln/examples/backward
gdb python
run ./backward_example.py
backtrace
```

***Output of backtrace:***
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bc6e84 in pthread_mutex_lock ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) backtrace
#0  0x00007ffff7bc6e84 in pthread_mutex_lock ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff5b49dec in __gthread_mutex_lock (__mutex=0x50)
    at /usr/include/c++/4.6/x86_64-linux-gnu/./bits/gthr-default.h:742
#2  0x00007ffff5b4de84 in std::mutex::lock (this=0x50)
    at /usr/include/c++/4.6/mutex:90
#3  0x00007ffff5b50cb2 in std::lock_guard<std::mutex>::lock_guard (
    this=0x7fffffffd1f0, __m=...) at /usr/include/c++/4.6/mutex:445
#4  0x00007ffff4f9f5e6 in opencog::Atom::getTruthValue (this=0x0)
    at /home/cosmo/opencog/opencog/atomspace/Atom.cc:111
#5  0x00007fffef7ecb0c in opencog::AtomSpace::getTV (this=0xa375d0, h=...)
    at /home/cosmo/opencog/opencog/atomspace/AtomSpace.h:449
#6  0x00007fffef7db0e1 in __pyx_pf_7opencog_9atomspace_9AtomSpace_14get_tv (
    __pyx_v_self=0x7ffff7f54170, __pyx_v_h=0x7ffff7f537c8)
    at /home/cosmo/opencog/build/opencog/cython/opencog/atomspace.cpp:4672
#7  0x00000000004f7496 in PyObject_Call ()
#8  0x00007fffef7e18fb in __pyx_pf_7opencog_9atomspace_4Atom_2tv___get__ (
    __pyx_v_self=0x7ffff7e3e310)
    at /home/cosmo/opencog/build/opencog/cython/opencog/atomspace.cpp:6944
#9  0x00007fffef7e6717 in __pyx_getprop_7opencog_9atomspace_4Atom_tv (
    o=0x7ffff7e3e310, x=0x0)
    at /home/cosmo/opencog/build/opencog/cython/opencog/atomspace.cpp:8815
#10 0x00000000004f3e78 in ?? ()
#11 0x00000000004fa73a in _PyObject_GenericGetAttrWithDict ()
#12 0x00000000004866be in PyEval_EvalFrameEx ()
#13 0x00000000004230da in ?? ()
#14 0x00000000004ef4a5 in ?? ()
#15 0x0000000000486d46 in PyEval_EvalFrameEx ()
#16 0x0000000000486e02 in PyEval_EvalFrameEx ()
#17 0x000000000048d930 in PyEval_EvalCodeEx ()
#18 0x0000000000486bb8 in PyEval_EvalFrameEx ()
#19 0x000000000048d930 in PyEval_EvalCodeEx ()
#20 0x0000000000486bb8 in PyEval_EvalFrameEx ()
#21 0x0000000000486e02 in PyEval_EvalFrameEx ()
#22 0x000000000048d930 in PyEval_EvalCodeEx ()
#23 0x00000000004246a1 in PyRun_FileExFlags ()
#24 0x000000000042492e in PyRun_SimpleFileExFlags ()
#25 0x0000000000425cb6 in Py_Main ()
#26 0x00007ffff68cb76d in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
#27 0x000000000041bb31 in _start ()
```

Here is the C++ output from Cython where the call was initiated:
```
  /* "/home/cosmo/opencog/opencog/cython/opencog/atomspace_details.pyx":291
 *         """ Return the TruthValue of an Atom in the AtomSpace """
 *         cdef tv_ptr tv
 *         tv = self.atomspace.getTV(deref(h.h))             # <<<<<<<<<<<<<<
 *         if (not tv.get() or tv.get().isNullTv()):
 *             pytv = TruthValue()
 */
  __pyx_v_tv = ((struct __pyx_obj_7opencog_9atomspace_AtomSpace *)__pyx_v_self)->atomspace->getTV((*((struct __pyx_obj_7opencog_9atomspace_Handle *)__pyx_v_h)->h));
```

Here is the line in Atom.cc:
https://github.com/opencog/opencog/blob/master/opencog/atomspace/Atom.cc#L111

**Comment by cosmoharrigan** [comment]
Closing: the referenced version is deprecated by new rule engine implementation.
