### ISSUE TITLE
PLN chainer throws, calls rule.calculate with null argument

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#652]
The PLN chainer sometimes calls rule.calculate with a null argument. The backtrace is:
```
terminate called after throwing an instance of 'opencog::RuntimeException'
  what():  PyMindAgent triggered runtime exception.Traceback (most recent call last):
  File "agent_finder.pyx", line 137, in opencog.agent_finder.run_agent (/home/cosmo/opencog/build/opencog/cython/opencog/agent_finder.cpp:2942)
  File "../opencog/python/pln/examples/tuffy/class/class_agent.py", line 59, in run
    AndCreationRule(self.chainer, num_predicates), [antecedent])
  File "/home/cosmo/opencog/opencog/python/pln/chainers.py", line 412, in backward_step
    results = self._apply_backward(rule, target_outputs=target_atoms)
  File "/home/cosmo/opencog/opencog/python/pln/chainers.py", line 631, in _apply_backward
    return self.apply_rule(rule, specific_inputs, final_outputs)
  File "/home/cosmo/opencog/opencog/python/pln/chainers.py", line 705, in apply_rule
    output_tvs = rule.calculate(inputs)
  File "/home/cosmo/opencog/opencog/python/pln/rule.py", line 76, in calculate
    result_tvs = self.formula(tvs)
  File "/home/cosmo/opencog/opencog/python/pln/rules/formulas.py", line 190, in andFormula
    return [TruthValue(total_strength, makeUpCount(tvs))]
  File "/home/cosmo/opencog/opencog/python/pln/rules/formulas.py", line 35, in makeUpCount
    return min(tv.count for tv in tvs)
ValueError: min() arg is an empty sequence
```
It seems that the ```apply_rule``` method calls ```rule.calculate``` with a null value for the ```inputs``` argument [here](https://github.com/opencog/opencog/blob/master/opencog/python/pln/chainers.py#L692), because ```_apply_backward``` did not declare any inputs, but it still invoked ```apply_rule``` [here](https://github.com/opencog/opencog/blob/master/opencog/python/pln/chainers.py#L619).

**Comment by cosmoharrigan** [comment]
Closing: the referenced version is deprecated by the new rule engine version.
